### ISSUE TITLE
Can't merge changes from development branch into master

### ISSUE THREAD

**Issue by samtaggart** [ourworldventures/www_ourworld_tf#23]
When I try to merge development into master, it takes me to a different repo altogether (timurgordon >>> ourworld_lp) and when I try to change that repo back to ourworldventures >>> www_ourworld_tf, I get an error.

<img width="1461" alt="Screenshot 2024-04-24 at 13 39 56" src="https://github.com/ourworldventures/www_ourworld_tf/assets/50134479/b53f8450-f215-477d-b9a1-d6fd104b37e5">

<img width="1454" alt="Screenshot 2024-04-24 at 13 40 15" src="https://github.com/ourworldventures/www_ourworld_tf/assets/50134479/1a63dda6-1085-4129-93b7-efb01a212c23">

I just want to merge the changes I made to the people page on development into the production site.

**Comment by samtaggart** [comment]
@ehab-hassan Can you check why there is a black mark over "Info" in the header

![Screenshot 2024-04-24 at 15 18 03](https://github.com/ourworldventures/www_ourworld_tf/assets/50134479/7a131ef5-39d8-45a9-9bef-c036035603b0)

**Comment by ehab-hassan** [comment]
fixed

**Comment by samtaggart** [comment]
@ehab-hassan I made a few quick fixes (sorry) and still facing the issue (cannot merge development to main). Why is this happening?
